### ISSUE TITLE
question about tree tables you considered?

### ISSUE THREAD

**Issue by nishihatapalmer** [carlca/PluginManager#1]
Hi, this is a quick follow up question about your choice of using the byteseek TreeTable.

You said you liked the fact that it had keybindings for the treetable.  Can I ask what other TreeTable components you considered when making your choice?  I'm updating my documentation and would like to get an idea of the competition!

Thanks,

Matt.

**Comment by carlca** [comment]
To be honest, all I found was as a result of searching for "multi column tree java" in https://ecosia.org. There were a couple of articles on Baeldung and countless messages on StackOverflow. There's a limit to how much SO I can take in a single sitting so that avenue didn't get pursued very far 😉 I assume there are a few commercial or open-source component packs out there but, apart from yours, I couldn't find any.

**Comment by nishihatapalmer** [comment]
Thanks.  I used an internal Netbeans tree table in earlier code I wrote, but have had nothing but trouble with it.  I even submitted bug reports years ago, and they are still debating whether to fix it, although they accept the bug exists.

It was what prompted me to write this, as I couldn't find a good Swing open source one.
